services:
  servesync.api:
    image: servesync.api
    build:
      context: .
      dockerfile: Presentation/ServeSync.API/Dockerfile
    ports:
        - "5000:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__Default=server=db;database=ServeSync;user=root;password=pbl6@2023
        - ConnectionStrings__Redis=redis
        - Jwt__Key=this_is_my_secret_key_for_authentication
        - Jwt__ExpiresInMinute=30
        - Jwt__RefreshTokenExpiresInDay=3
        - Email__Username=minishop.pbl3@gmail.com
        - Email__Password=yimcdficrfejnvfd
        - ForgetPasswordSetting__AllowedClients__0=http://localhost:4200
        - ForgetPasswordSetting__AllowedClients__1=http://localhost:4300
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: mysql
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=pbl6@2023
    ports:
      - "33306:3306"
    volumes:
      - servesync:/var/lib/mysql
  
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  servesync:
