services:
  servesync.api:
    image: servesync.api
    build:
      context: .
      dockerfile: Presentation/ServeSync.API/Dockerfile
    ports:
        - "5000:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__Default=server=db;database=ServeSync;user=root;password=pbl6@2023
        - ConnectionStrings__Redis=redis
        - ConnectionStrings__HangFire=server=db;database=ServeSync_HangFire;user=root;password=pbl6@2023
        - ConnectionStrings__HangFireMaster=server=db;database=sys;user=root;password=pbl6@2023
        - Jwt__Key=this_is_my_secret_key_for_authentication
        - Jwt__ExpiresInMinute=30
        - Jwt__RefreshTokenExpiresInDay=3
        - Email__Username=minishop.pbl3@gmail.com
        - Email__Password=yimcdficrfejnvfd
        - ForgetPasswordSetting__ExpiresInMinute=30
        - Cloudinary__CloudName=dboijruhe
        - Cloudinary__ApiKey=431114562135728
        - Cloudinary__ApiSecret=tmDw4SrmffqZp2hA2tiDDZgemTU
        - ForgetPasswordSetting__AllowedClients__0=http://localhost:4200
        - ForgetPasswordSetting__AllowedClients__1=http://localhost:4300
        - MongoDb__Host=mongoDb
        - MongoDb__Port=27017
        - MongoDb__UserName=root
        - MongoDb__Password=pbl62023
        - TZ=SE Asia Standard Time
    restart: always
    depends_on:
      - db
      - redis
      
  db:
    image: mysql
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=pbl6@2023
    ports:
      - "33306:3306"
    volumes:
      - servesync_db:/var/lib/mysql
    restart: always
    
  mongoDb:
    image: mongo
    ports:
      - "27018:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pbl62023
    volumes:
      - servesync_mongo:/data/db
  
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  servesync_db:
  servesync_mongo:
