services:
  servesync.api:
    image: servesync.api
    build:
      context: .
      dockerfile: Presentation/ServeSync.API/Dockerfile
    ports:
        - "5000:80"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__Default=server=db;database=ServeSync;user=root;password=pbl6@2023
        - ConnectionStrings__Redis=redis
        - Jwt__Key=this_is_my_secret_key_for_authentication
    depends_on:
      - db
      - redis
  db:
    image: mysql
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=pbl6@2023
    ports:
      - "33306:3306"
    volumes:
      - servesync:/var/lib/mysql
  
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  servesync:
